env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/work"
    OUT_DIRECTORY: "/tmp/work/source/out/target/product/*"
    DEVICE: "RMX1941"
    DT_LINK: "https://github.com/P-Salik/android_recovery_realme_RMX1941"
    DT_PATH: "device/realme/RMX1941"
    MANIFEST: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git"
    MANIFEST_BRANCH: "twrp-12.1"
    GH_TOKEN: "ENCRYPTED[051a815373ace22a99f09b04219929ee702eb0907e6018be14cb94c3a52968517f4435d433ad785a3b78ff6595886a92]"
    GH_USERNAME: "P-Salik"
    GH_USEREMAIL: "peersalik16@gmail.com"
    SF_USERNAME: "ENCRYPTED[3c54b041265e80b81565f71f33abcae127aa91d572e6f500cfdab3fc3fa4ecc7bf462dfc8ee372001da81bbcd647240f]"
    SF_PASS: "ENCRYPTED[15310dc017ff3eda251257f94f235e264f7e7c054f6ebc95f871349cf4222bd4ed88d0137836c9d524f587442ab4978e]"
    TG_TOKEN: "ENCRYPTED[4c6210d835e56f74de40aa822691d60b9f60527f2c9e814f844e11fa6ba1d010ad0cd33761a81cdee589cd06c5f2a1b2]"
    TG_CHAT: "-1001662836130"

task:
    name: Build
    timeout_in: 120m
    container:
      image: ubuntu:latest
      cpu: 4
      memory: 16
    env_script:
      - env
    setup_script:
      - ./setup.sh
    build_script:
      - ./build.sh
